//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageWebMic.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulos_contenido_media
    {
        public int id { get; set; }
        public Nullable<int> media_id { get; set; }
        public Nullable<int> articulos_contenido_id { get; set; }
    
        public virtual media media { get; set; }
        public virtual articulos_contenido articulos_contenido { get; set; }
    }
}
