//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageWebMic.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulos_contenido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public articulos_contenido()
        {
            this.articulos_contenido1 = new HashSet<articulos_contenido>();
            this.media1 = new HashSet<media>();
            this.articulos_contenido_media = new HashSet<articulos_contenido_media>();
            this.slideshow = new HashSet<slideshow>();
        }
    
        public int id { get; set; }
        public string id_title { get; set; }
        public string titulo { get; set; }
        public string subtitulo { get; set; }
        public string contenido { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string image_presentation_1 { get; set; }
        public string image_presentation_2 { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
        public string tags { get; set; }
        public Nullable<bool> avalible_edit { get; set; }
        public Nullable<bool> avalible_childrens { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulos_contenido> articulos_contenido1 { get; set; }
        public virtual articulos_contenido articulos_contenido2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<media> media1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulos_contenido_media> articulos_contenido_media { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<slideshow> slideshow { get; set; }
    }
}
