//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageWebMic.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banners
    {
        public int id { get; set; }
        public string url { get; set; }
        public string image_url { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
