//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageWebMic.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cambio_combustible_precio
    {
        public int id { get; set; }
        public Nullable<int> id_cambio_combustible { get; set; }
        public string id_combustible { get; set; }
        public string precio { get; set; }
    
        public virtual cambio_combustible cambio_combustible { get; set; }
        public virtual combustible combustible { get; set; }
    }
}
