//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageWebMic.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public System.Guid Id { get; set; }
        public long RowId { get; set; }
        public string Name { get; set; }
        public string Original { get; set; }
        public string Type { get; set; }
        public long Size { get; set; }
        public System.DateTime UploadTime { get; set; }
        public byte[] Data { get; set; }
        public byte[] Preview { get; set; }
        public string Path { get; set; }
        public byte[] Meta { get; set; }
        public int media_album_id { get; set; }
    
        public virtual media_album media_album { get; set; }
    }
}
