//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageWebMic.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class media_album_user
    {
        public int id { get; set; }
        public int media_album_id { get; set; }
        public string usuario_id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual media_album media_album { get; set; }
    }
}
