//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageWebMic.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class media_combustible
    {
        public int id { get; set; }
        public Nullable<int> cambio_combustible_id { get; set; }
        public string url { get; set; }
        public string type { get; set; }
        public Nullable<int> size { get; set; }
        public string name { get; set; }
    
        public virtual cambio_combustible cambio_combustible { get; set; }
    }
}
