//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageWebMic.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slideshow
    {
        public int id { get; set; }
        public string url_image { get; set; }
        public string text_html { get; set; }
        public Nullable<int> id_articulo { get; set; }
        public Nullable<bool> active { get; set; }
        public string type { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<bool> isServer { get; set; }
        public string type_name { get; set; }
        public string thumb { get; set; }
    
        public virtual articulos_contenido articulos_contenido { get; set; }
    }
}
