//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageWebMic.Areas.Languajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseAdmin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PageWebMic.Areas.Languajes.BaseAdmin", typeof(BaseAdmin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:18499/CustomDataProvider/FileHandlerJpg/.
        /// </summary>
        public static string ApiServiceJpgView {
            get {
                return ResourceManager.GetString("ApiServiceJpgView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:18499/CustomDataProvider/FileHandlerPdf/.
        /// </summary>
        public static string ApiServicePdfView {
            get {
                return ResourceManager.GetString("ApiServicePdfView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:18499/CustomDataProvider/FileHandler?objectContext=C5F260DD3787.
        /// </summary>
        public static string ApiServiceUploadFile {
            get {
                return ResourceManager.GetString("ApiServiceUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS.
        /// </summary>
        public static string namePage {
            get {
                return ResourceManager.GetString("namePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Álbum.
        /// </summary>
        public static string Ralbum {
            get {
                return ResourceManager.GetString("Ralbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banners.
        /// </summary>
        public static string Rbanners {
            get {
                return ResourceManager.GetString("Rbanners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combustible.
        /// </summary>
        public static string Rcombustible {
            get {
                return ResourceManager.GetString("Rcombustible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuraciones.
        /// </summary>
        public static string Rconfiguration {
            get {
                return ResourceManager.GetString("Rconfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenido.
        /// </summary>
        public static string Rcontenido {
            get {
                return ResourceManager.GetString("Rcontenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenido Pagina.
        /// </summary>
        public static string RContenidoContenido {
            get {
                return ResourceManager.GetString("RContenidoContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string Rcrear {
            get {
                return ResourceManager.GetString("Rcrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Combustible.
        /// </summary>
        public static string RcrearCombustible {
            get {
                return ResourceManager.GetString("RcrearCombustible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear nuevo.
        /// </summary>
        public static string RcrearNuevo {
            get {
                return ResourceManager.GetString("RcrearNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direcciones.
        /// </summary>
        public static string Rdirecciones {
            get {
                return ResourceManager.GetString("Rdirecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidorcarburos.
        /// </summary>
        public static string Rhidrocarburos {
            get {
                return ResourceManager.GetString("Rhidrocarburos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Rinicio {
            get {
                return ResourceManager.GetString("Rinicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visor de Imágenes Inicio.
        /// </summary>
        public static string RListaSlideshow {
            get {
                return ResourceManager.GetString("RListaSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manegador Tipos De Archivos.
        /// </summary>
        public static string RmanagerType {
            get {
                return ResourceManager.GetString("RmanagerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Usuarios.
        /// </summary>
        public static string RmanagerUsuarios {
            get {
                return ResourceManager.GetString("RmanagerUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manejador combustible.
        /// </summary>
        public static string RmanejadorCombustible {
            get {
                return ResourceManager.GetString("RmanejadorCombustible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Rmedia {
            get {
                return ResourceManager.GetString("Rmedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Combustible.
        /// </summary>
        public static string Rprecio_combustible {
            get {
                return ResourceManager.GetString("Rprecio_combustible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Album.
        /// </summary>
        public static string RroleAlbum {
            get {
                return ResourceManager.GetString("RroleAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Usuarios.
        /// </summary>
        public static string Rroles {
            get {
                return ResourceManager.GetString("Rroles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visor de imagenes.
        /// </summary>
        public static string RstarSlide {
            get {
                return ResourceManager.GetString("RstarSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos De Archivos.
        /// </summary>
        public static string RtypeFile {
            get {
                return ResourceManager.GetString("RtypeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string Rusers {
            get {
                return ResourceManager.GetString("Rusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viceministerios.
        /// </summary>
        public static string Rviceministerios {
            get {
                return ResourceManager.GetString("Rviceministerios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas las Carpetas.
        /// </summary>
        public static string viewAlltree {
            get {
                return ResourceManager.GetString("viewAlltree", resourceCulture);
            }
        }
    }
}
